language: c
install: wget https://raw.githubusercontent.com/ocaml/ocaml-travisci-skeleton/master/.travis-docker.sh
script: bash -ex .travis-docker.sh
services:
  - docker
sudo: false

env:
  global:
  - PACKAGE="ocaml-migrate-parsetree"
  - PRE_INSTALL_HOOK="cd /home/opam/opam-repository && git pull origin master && opam update -u -y"

matrix:
  include:
  - env: DISTRO=debian-testing OCAML_VERSION=4.02.3
    stage: OMP
  - env: DISTRO=debian-stable OCAML_VERSION=4.03.0
    stage: OMP
  - env: DISTRO=debian-unstable OCAML_VERSION=4.04.2
    stage: OMP
  - env: DISTRO=ubuntu-16.04 OCAML_VERSION=4.05.0
    stage: OMP
  - env: DISTRO=alpine OCAML_VERSION=4.06.1
    stage: OMP
  - env: DISTRO=alpine OCAML_VERSION=4.07.1
    stage: OMP
  - env: DISTRO=debian-testing OCAML_VERSION=4.02.3 PACKAGE=ocaml-migrate-parsetree-ocamlbuild
    stage: OMP-ocb
  - env: DISTRO=debian-stable OCAML_VERSION=4.03.0 PACKAGE=ocaml-migrate-parsetree-ocamlbuild
    stage: OMP-ocb
  - env: DISTRO=debian-unstable OCAML_VERSION=4.04.2 PACKAGE=ocaml-migrate-parsetree-ocamlbuild
    stage: OMP-ocb
  - env: DISTRO=ubuntu-16.04 OCAML_VERSION=4.05.0 PACKAGE=ocaml-migrate-parsetree-ocamlbuild
    stage: OMP-ocb
  - env: DISTRO=alpine OCAML_VERSION=4.06.1 PACKAGE=ocaml-migrate-parsetree-ocamlbuild
    stage: OMP-ocb
  - env: DISTRO=alpine OCAML_VERSION=4.07.1 PACKAGE=ocaml-migrate-parsetree-ocamlbuild
    stage: OMP-ocb
